#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"
GRADLE_USER_HOME="$DIR/.gradle"

exec "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
